version: '3'
services: 
  db:  
    restart: always
    image: mysql
    container_name: httpbasic_mysql
    ports:
    - "9999:3306"
    environment:
     MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
     MYSQL_ROOT_PASSWORD: root   
     MYSQL_DATABASE: httpbasic
     MYSQL_USER: httpbasic
     MYSQL_PASSWORD: httpbasic
     MYSQL_ROOT_HOST: '%'    
    healthcheck:
      test: "/usr/bin/mysql --user=httpbasic --password=httpbasic--execute \"SHOW DATABASES;\""
      interval: 60s
      timeout: 60s
      retries: 10
    networks:
        - backbone  
      
  server-code:
    restart: always
    container_name: httpbasicapi
    build:
      context: .
      dockerfile: docker-service
    depends_on:
     - db     
    expose:
      - "8080"
    ports:
      - 8080:8080
    environment:
      WAIT_HOSTS: httpbasic_mysql:3306      
    networks:
        - backbone  
      
  ui-code:
    restart: always
    container_name: angularcode
    build:
      context: src\main\webapp
      dockerfile: angular-code
    links:
       - server-code
    depends_on:
     - server-code
    expose:
      - "4200"
    ports:
      - 4200:80
    networks:
        - backbone  
      
networks:
  backbone:
   driver: bridge
    
    
    